### ISSUE TITLE
Disable autoscrolling for scrollable childrens

### ISSUE THREAD

**Issue by luuuppi** [stackblitz/use-stick-to-bottom#7]
If there's way to disable an autoscrolling for scrollable `contentRef` childrens, like a fenced-code-blocks with `overflow-x: auto`?

**Comment by samdenty** [comment]
I don't believe we listen to the scroll event for nested code-blocks, could you provide an example/screen recording of the issue you can fork this project on stackblitz if you want to provide a demo https://stackblitz.com/edit/github-m9hkpw.

If it's the case we're incorrectly filtering out events, i'm curious to what code is doing that:

we guard against it here 

https://github.com/stackblitz/use-stick-to-bottom/blob/cf0f46a4779f052c587250259ceb12af221cb5fb/src/useStickToBottom.ts#L338

if you want to debug it yourself feel free to send a fix, otherwise a demo stackblitz project would be amazing to help me fix the issue

**Comment by luuuppi** [comment]
I tested it and found, that the problem is on my side. Sorry for misleading you
